version: '3.5'


networks:
  inception: {}

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: always


volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tblaase/data/mariadb

  wordpress_v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tblaase/data/wordpress